import initScrollSuave from './modules/scroll-suave.js';
import initAnimacaoScroll from './modules/scroll-animacao.js';
import initAccordion from './modules/accordion.js';
import initTabNav from './modules/tabnav.js';
import iniTooltip from './modules/tooltip.js';
import initModal from './modules/modal.js';
import initDropDownMenu from './modules/dropdown-menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initFuncionamento from './modules/funcionamento.js';
import initFetchAnimais from './modules/fetch-animais.js';
import initFetchBitcoin from './modules/fetch-bitcoin.js';

initFuncionamento();
initMenuMobile();
initModal();
iniTooltip();
initScrollSuave();
initAnimacaoScroll();
initAccordion();
initTabNav();
initDropDownMenu();
initFetchAnimais();
initFetchBitcoin();
